import type { GeneratedPaper } from '@vedaai/shared';

const DIFF_LABELS: Record<string, string> = {
  easy: 'Easy',
  medium: 'Moderate',
  hard: 'Hard',
};

const TYPE_LABELS: Record<string, string> = {
  mcq: 'MCQ',
  short_answer: 'Short Answer',
  long_answer: 'Long Answer',
  true_false: 'True/False',
  fill_blanks: 'Fill Blanks',
};

export async function downloadPaperAsPDF(paper: GeneratedPaper): Promise<void> {
  // Dynamic import to avoid SSR issues
  const [jsPDFModule] = await Promise.all([import('jspdf')]);
  const jsPDF = jsPDFModule.default;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const addPageIfNeeded = (height: number) => {
    if (y + height > 270) {
      doc.addPage();
      y = 20;
    }
  };

  // Header
  doc.setFillColor(232, 76, 58);
  doc.rect(0, 0, pageWidth, 12, 'F');
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255);
  doc.text('VedaAI Assessment Platform', margin, 8);
  doc.text(`Generated: ${new Date(paper.generatedAt).toLocaleDateString()}`, pageWidth - margin, 8, { align: 'right' });
  y = 20;

  // Title
  doc.setFontSize(18);
  doc.setTextColor(20, 27, 36);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(paper.title, contentWidth);
  doc.text(titleLines, pageWidth / 2, y, { align: 'center' });
  y += titleLines.length * 8 + 2;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(88, 99, 111);
  doc.text(`Subject: ${paper.subject}  |  Grade: ${paper.grade}  |  Total Marks: ${paper.totalMarks}  |  Duration: ${paper.duration || 'N/A'}`, pageWidth / 2, y, { align: 'center' });
  y += 8;

  // Divider
  doc.setDrawColor(232, 76, 58);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Student info box
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.rect(margin, y, contentWidth, 24);
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  doc.text('Name: ____________________________', margin + 4, y + 8);
  doc.text('Roll No: ________________', margin + 4 + contentWidth / 2, y + 8);
  doc.text('Section: ________________', margin + 4, y + 18);
  doc.text('Date: __________________', margin + 4 + contentWidth / 2, y + 18);
  y += 32;

  // Sections
  for (const section of paper.sections) {
    addPageIfNeeded(30);

    // Section header
    doc.setFillColor(245, 245, 245);
    doc.rect(margin, y, contentWidth, 10, 'F');
    doc.setFontSize(12);
    doc.setTextColor(20, 27, 36);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin + 4, y + 7);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(88, 99, 111);
    doc.text(`[${section.totalMarks} Marks]`, pageWidth - margin - 4, y + 7, { align: 'right' });
    y += 13;

    doc.setFontSize(9);
    doc.setTextColor(88, 99, 111);
    doc.setFont('helvetica', 'italic');
    doc.text(section.instruction, margin + 4, y);
    y += 7;

    // Questions
    for (let qi = 0; qi < section.questions.length; qi++) {
      const q = section.questions[qi];
      addPageIfNeeded(20);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(20, 27, 36);
      const qNum = `Q${qi + 1}.`;
      doc.text(qNum, margin + 2, y);

      doc.setFont('helvetica', 'normal');
      const qTextLines = doc.splitTextToSize(q.text, contentWidth - 30);
      doc.text(qTextLines, margin + 12, y);

      // Marks + difficulty on right
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`[${q.marks}M | ${DIFF_LABELS[q.difficulty] || q.difficulty}]`, pageWidth - margin - 2, y, { align: 'right' });

      y += qTextLines.length * 5 + 2;

      // MCQ options
      if (q.type === 'mcq' && q.options) {
        for (const opt of q.options) {
          addPageIfNeeded(6);
          doc.setFontSize(9);
          doc.setTextColor(60, 60, 60);
          const optLines = doc.splitTextToSize(opt, contentWidth - 20);
          doc.text(optLines, margin + 18, y);
          y += optLines.length * 5;
        }
      }

      y += 4;
    }

    y += 6;
  }

  // Footer
  const totalPages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, 290, { align: 'center' });
    doc.text('Generated by VedaAI', margin, 290);
  }

  doc.save(`${paper.title.replace(/[^a-z0-9]/gi, '_')}_QuestionPaper.pdf`);
}
